/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'ap-northeast-2',
  aws_cognito_identity_pool_id:
    'ap-northeast-2:e88fbc14-a07b-4ca8-a855-2d3e193e2c4c',
  aws_cognito_region: 'ap-northeast-2',
  aws_user_pools_id: 'ap-northeast-2_cRvk2s0jW',
  aws_user_pools_web_client_id: '7gi7pi2p1401lli3qaj9la0ocl',
  oauth: {},
  aws_appsync_graphqlEndpoint:
    'https://er2c2n6g2rfq3duq5x52fbq6yq.appsync-api.ap-northeast-2.amazonaws.com/graphql',
  aws_appsync_region: 'ap-northeast-2',
  aws_appsync_authenticationType: 'API_KEY',
  aws_appsync_apiKey: 'da2-xfh7xslpmjgcjdyvvkkbycsqhy',
};

export default awsmobile;
